### ISSUE TITLE
Unable to specify the pygments formatter to use on received output

### ISSUE THREAD

**Issue by ssbarnea** [pawamoy/markdown-exec#11]
**Describe the bug**
Executed problems can produce ANSI output, which mkdocs can render using the `ansi` pygments formatter.

Still, this plugin does not allow us to specify which formatter to use and uses markdown.

This means that two undesired things will happen when documenting program output:
- if the output contains ANSI, the rendering will be messed
- if the output is plain text, some random keywords will be highlighted in the output

**To Reproduce**
1. Gran a CLI tool that produces ANSI output, like [ANSI test file](https://gist.github.com/mxmerz/92e97cd27857a9ba787b)
2. Add a markdown-exec block the runs it
3. What the rendered output.

**Expected behavior**

We need to allow exec to work similarly to already valid ANSI formatter
>   \`\`\`ansi
>   \`\`\`

Note that while testing, you might miss to see the colors but the ANSI will render fine. If you use inspect, you will see that class colors were added to the HTML and they will render once you add the extra css needed for them.

**Screenshots**

Example of an [ANSI test file](https://gist.github.com/mxmerz/92e97cd27857a9ba787b) using the block above:

![](https://sbarnea.com/ss/Screen-Shot-2023-01-26-12-34-19.76.png)

Example of undesired markdown coloring on a command line output:
![](https://sbarnea.com/ss/Screen-Shot-2023-01-26-12-46-59.28.png)

Example of failure to process ANSI escapes:
![](https://sbarnea.com/ss/Screen-Shot-2023-01-26-12-49-43.28.png)

**System (please complete the following information):**
- `Markdown Exec` version: 1.0.0
- Python version: 3.11
- OS: MacOS

**Additional context**

I did observe that there is already support for recognizing the output as JSON or HTML, so I guess it should not be too hard to add an option where we can declare the expected output format, so it would render correctly.

If you could give some hints on how this can be addressed, I would be happy to contribute a PR. I was quite pleased about the current plugin behavior and its really good documentation.

**Comment by pawamoy** [comment]
Not sure to understand: isn't the [result option](https://pawamoy.github.io/markdown-exec/usage/#wrap-result-in-a-code-block) working for your use-case?

**Comment by pawamoy** [comment]
Did you install a Pygment extension or something? I can't seem to display the colors with an `ansi` code block (or `terminal`, or other equivalent languages: https://pygments.org/docs/formatters/).

**Comment by ssbarnea** [comment]
To enable `ansi` formatting in pygments, you need to install `pygments-ansi-color` package. I will post some extra info about it in the following days.

**Comment by pawamoy** [comment]
That's great, thanks! I think providing the stylesheet is outside the scope of markdown-exec, but we can definitely put it in the docs.

**Comment by pawamoy** [comment]
Actually just released v1.2.0 which provides the `ansi` extra so you don't have to depend on `pygments-ansi-color` and add the CSS file yourself :slightly_smiling_face:
