### ISSUE TITLE
bug: Directory change dos not persist between code blocks executed on the same session

### ISSUE THREAD

**Issue by NikosAlexandris** [pawamoy/markdown-exec#32]
### Description of the bug

Given that the current working directory is part of the _state_ when executing code in a shell,
then the state does _not_ persist between executed code blocks when changing to another directory.

### To Reproduce

Enter in a directory, print its name and list files inside it : 

~~~ bash
```
bash exec="true" result="ansi" session="somesession" source="above"
cd somedirectory/
pwd
```
~~~
OR

~~~ bash
``` bash exec="true" result="ansi" session="somesession" source="above"
cd somedirectory/
ls .
```
~~~

Print the current directory's name (or list its content), expected to be `somedirectory` (or the same content) from the previous commands : 

~~~ bash
``` bash exec="true" result="ansi" session="somesession" source="above"
pwd
```
~~~

### Expected behavior

Given that the current working directory is part of the _state_, executing subsequent code blocks on the same _session_ should remember previously executed code blocks that change the directory.

### Environment information
```bash
python -m markdown_exec.debug
```

- __System__: Linux-6.7.0-arch3-1-x86_64-with-glibc2.38
- __Python__: cpython 3.11.6
- __Environment variables__:
- __Installed packages__:
  - `markdown-exec` v1.8.0

**Comment by pawamoy** [comment]
Hello, thanks for the report.

So, actually, sessions are not supported for the `sh` or `bash` languages.

To bring support, we would have to run a process in the background and feed it input. I believe this would maintain the CWD.

About the output, I'm not sure how we would handle prompts. Stripping last line after each input/output? This won't support multi-line prompts. Maybe a `hide_prompt` option would do the trick, where if true we'd set the right env bar to something we can remove from each output.

**Comment by NikosAlexandris** [comment]
I didn't pay attention to the notice this works for Python and Pycon only :-/.  Anyhow, it would be useful to stick the current working directory across code blocks running in the same session.  However, for my use case, I prefer a single command output only. That is, show the last command's output.

ps- Reading in the unedited comment about _hiding_, though, gives me an idea to work-around my current use-case without using a _session_.  In a How-To, I am trying to say something like : 

- we navigate to ... 
  ~~~ bash
  ``` bash exec="true" source="above"
  cd somedirectory/
  ```
  ~~~

- we next run _this_ command
  ~~~ bash
  ```bash exec="true" source="above"
   somecommand . --some-option
   ```
  ~~~

So, for now, maybe the second command can be

  ~~~ bash
  ```bash exec="true" source="above"
  cd somedirectory/  # markdown-exec: hide
  somecommand . --some-option
  ```
  ~~~

while hiding the first line (?).

Will try.

**Comment by NikosAlexandris** [comment]
> So, for now, maybe the second command can be
> 
> ```shell
> ```bash exec="true" source="above"
> cd somedirectory/  # markdown-exec: hide
> somecommand . --some-option
> ```
> ```
> 
> while hiding the first line (?).
> 
> Will try.

That seems to work nicely for my use case.  Needless to repeat, this plugin is very useful! Thank you @pawamoy.

**Comment by pawamoy** [comment]
Since sessions are not yet supported for Bash code blocks, I'll close this issue in favor of https://github.com/pawamoy/markdown-exec/issues/53.
