### ISSUE TITLE
feat: Support specifying terminal width

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/markdown-exec#34]
### Discussed in https://github.com/pawamoy/markdown-exec/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **NikosAlexandris** January 26, 2024</sup>
Rich table output in the console is truncated (i.e. table column names are incomplete), for example : https://nikosalexandris.github.io/rekx/how_to/inspect/. See in [this pages source code](https://github.com/NikosAlexandris/rekx/raw/main/docs/how_to/inspect.md) the output of  commands wrapped inside a block

``` markdown
    ``` bash exec="true" result="ansi" source="above"
    ```
```

Any idea how to "fix" this ?
See also : https://github.com/squidfunk/mkdocs-material/issues/4964#issuecomment-1898039123.  </div>

---

We could provide a new option to set the terminal width in the subprocess. Basically `export COLUMNS=1000`.

@NikosAlexandris could try the following and let me know if it fixes your issue?

````md
``` bash exec="true" result="ansi" source="above"
export COLUMNS=1000  # markdown-exec: hide
rekx inspect data/single_file/SISin202001010000004231000101MA.nc
```
````

**Comment by NikosAlexandris** [comment]
> We could provide a new option to set the terminal width in the subprocess. Basically `export COLUMNS=1000`.
> 
> @NikosAlexandris could try the following and let me know if it fixes your issue?
> 
> ```
> ``` bash exec="true" result="ansi" source="above"
> export COLUMNS=1000  # markdown-exec: hide
> rekx inspect data/single_file/SISin202001010000004231000101MA.nc
> ```
> ```

Yes! It works.

In the screenshot, above is _without_ `export COLUMNS=1000` and below is _with_ it : 

![2024-01-26T22:55:53,600430850+02:00](https://github.com/pawamoy/markdown-exec/assets/7046639/3ba03dac-d1f2-4f06-808a-7e55617df15d)

That looks so much better!  Had we also a full-width option, it'd be ideal.  Kind regards @pawamoy.

**Comment by NikosAlexandris** [comment]
Can such an option (here `export COLUMNS=1000`) be pre-set globally ?

**Comment by pawamoy** [comment]
Thanks for reporting back :slightly_smiling_face: 

> Can such an option (here export COLUMNS=1000) be pre-set globally ?

Good idea, I'll think about it :thinking: 

> Had we also a full-width option, it'd be ideal.

What do you mean exactly by full-width option?

**Comment by NikosAlexandris** [comment]
> > Had we also a full-width option, it'd be ideal.
> 
> What do you mean exactly by full-width option?

Please have a look at https://jupyterbook.org/en/stable/content/layout.html#full-width-code-cells.

**Comment by pawamoy** [comment]
I see, thanks. This is irrelevant to Markdown Exec though, as it's not responsible for the actual (HTML) rendering of code blocks.
