### ISSUE TITLE
feature: Inline Plotly Graphs

### ISSUE THREAD

**Issue by loricah** [pawamoy/markdown-exec#51]
### Is your feature request related to a problem? Please describe.
I have several Python code blocks in a session, and the final one is meant to show a plotly graph. Instead, the graph is launched on a separate window. 

### Describe the solution you'd like
I would like to call `fig.show()` and the interactive graphs would appear the same way any other output would. 

### Describe alternatives you've considered
/

### Additional context
/

**Comment by pawamoy** [comment]
Try this:

```python
fig.show(renderer="svg")
```

You could also try the `notebook` renderer. See all renderers here: https://github.com/plotly/plotly.py/blob/51eb5ea9fefda27bccfdb21e660b8d4035cef3b0/packages/python/plotly/plotly/io/_renderers.py#L404. More info on renderers here: https://plotly.com/python/renderers/.

**Comment by loricah** [comment]
@pawamoy, thank you for the quick response. I have tried specifying a renderer like you instructed, and each time it simply prints the html to the terminal that my docs are launched on. I can’t display anything that way.

**Comment by pawamoy** [comment]
I figured it out :slightly_smiling_face: 

````md
```python exec="true" html="true"
import plotly.express as px

fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
print(fig.to_html(full_html=False, include_plotlyjs="cdn"))
```
````

**Comment by pawamoy** [comment]
I believe it's a good enough solution so I'll close this issue, feel free to comment further :slightly_smiling_face:

**Comment by loricah** [comment]
Just commenting to say thank you, this works perfectly!
