### ISSUE TITLE
bug:  output doesn't render when empty

### ISSUE THREAD

**Issue by awennersteen** [pawamoy/markdown-exec#57]
### Description of the bug
[A recent PR>](https://github.com/pawamoy/markdown-exec/commit/4337d1337b5aedd190627287f7e0a48000396902) seems to have changed drastically the behaviour of this plugin by not rendering empty output. 

Rendering such cases is useful for example when making tutorials or examples, as you can insert comments between codeblocks in a session.

Both behaviors seem very desireable though. Perhaps this can be toggleable?

An example where this affected us:

https://pasqal-io.github.io/qadence/latest/tutorials/digital_analog_qc/analog-qcl/
with source:
https://github.com/pasqal-io/qadence/blob/main/docs/tutorials/digital_analog_qc/analog-qcl.md

### To Reproduce
```python exec="on"
a=1+1
```

### Expected behavior
The above should render

### Proposal
To keep both options is it possible to support syntax such as

```python exec="on" render="true"
a=1+1
```

I'd be happy to give this a shot an implement it but would like to know the desired direction, and perhaps some pointers to get started.

Thanks for the great plugin!

**Comment by pawamoy** [comment]
Hi @awennersteen, thanks for the report!

Right, I was too quick and didn't think of code blocks that are executed for sessions and also show the source. Let me fix this :)

**Comment by awennersteen** [comment]
Thanks @pawamoy!
Impossible to consider all use-cases in advance

As I said I'd be happy to implement it to save you some time, but I'd probably need a sentence or two of description of what should be the desired interface and behavior.
Whatever is the easiest for you :)

**Comment by jpmoutinho** [comment]
Seems to have fixed it @pawamoy, thanks a lot for the quick reply

**Comment by tylerh111** [comment]
I had the same issue. Version 1.9.2 fixes it. Thanks!
