### ISSUE TITLE
bug: broken metadata on 1.9.3 release (author)

### ISSUE THREAD

**Issue by ssbarnea** [pawamoy/markdown-exec#64]
Check https://pypi.org/project/markdown-exec/ and see the author link is broken. That is due to some broken metadata.

![](https://sbarnea.com/ss/Screen-Shot-2024-12-03-11-07-35.49.png)

**Comment by pawamoy** [comment]
Issue lies in warehouse: https://github.com/pypi/warehouse/issues/16496. Closing since we just have to wait here :slightly_smiling_face:
