### ISSUE TITLE
Isssue with Abbreviations

### ISSUE THREAD

**Issue by fabge** [pawamoy/markdown-exec#8]
There seems to be an issue when the [`abbr`](https://squidfunk.github.io/mkdocs-material/reference/tooltips/) extension is used in conjunction with markdown-exec.

I have following markdown content (Screenshot as I cannot have two a ``` fence inside another)

![grafik](https://user-images.githubusercontent.com/21140791/192783831-4749a70c-4956-45b6-ae90-f7b0390f7ef1.png)

The final output however has the abbreviation glossary attached below the markdown-exec code fence:

![grafik](https://user-images.githubusercontent.com/21140791/192784066-16d612e4-d555-47fc-be3f-2b10b77fdfe8.png)

**Comment by pawamoy** [comment]
Hi, thanks for the report!

You can definitely write a code block in a code block with this syntax:

`````
````md
# Support

```python exec="true"
import platform
```

Lorem ipsum
````
`````

I'll try to replicate :slightly_smiling_face:

**Comment by pawamoy** [comment]
Unfortunately I cannot replicate. Did you actually add the `abbr` extension to `markdown_extensions` in `mkdocs.yml`?
If you did, then please set up a public repository that reproduces the issue.

**Comment by pawamoy** [comment]
Closing for lack of information.
